# Generated by Django 5.1 on 2024-09-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_auteur_article_auteur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('Peut_Modifier_Article', 'peut modifier un article')]},
        ),
    ]
